### ISSUE TITLE
Problems migrating to v5

### ISSUE THREAD

**Issue by nikparo** [styled-system/styled-system#559] opened 2019-06-15 09:35 UTC
Hi,
I've had a few problems upgrading to v5 (from v3).

1. **Breakpoints** stopped working, since they were unitless. (E.g `768` rather than `'768px'`). Not sure whether breakpoints are handled by styled-system or styled-components, but it may be good to mention in the migration guide?

2. My **variants** have been css strings, however these no longer work - every character now goes on its own line. I know I can rewrite the variants as style objects, but is dropping support for style strings intended and done for a reason? Code example:
    ``` js
    theme.borderBoxes = {
      white: `
        background-color: white;
        border: 1px solid rgba(0,0,0,0.14);
      `,
    };
    ```
    is now added to the stylesheet as:
    ``` css
    .iCnWRS {
      1: b;
      2: a;
      3: c:
      4: k;
      5: g;
      ...
    }
    ```

3. **defaultProps** get rendered after props passed to a component. (Potentially #348 and/or #499? Not sure if the fix mentioned at the end of #348 is meant to be in v5.0.6) Example:

    ``` js
    const Box = styled('div')(compose(space, layout));
    Box.defaultProps = { m: 0 };
    ```

    A Box rendered as such:
    ``` jsx
    <Box mx="20px" />
    ```

    gets css like:
    ``` css
    .hPVxJS {
      margin-left: 20px;
      margin-right: 20px;
      margin: 0;
    }
    ```

**Comment by ransjo** [comment] 2019-06-20 10:03
For #3, what if createParser were to iterate over config instead of props (see https://github.com/styled-system/styled-system/issues/499#issuecomment-503959544), to generate the same style order as v4 ?

**Comment by jxnblk** [comment] 2019-06-20 15:25
Thanks for reporting! If you're not doing so already, I'd certainly recommend bumping one major version at a time to address the breaking changes incrementally.

> Breakpoints stopped working, since they were unitless. (E.g 768 rather than '768px'). Not sure whether breakpoints are handled by styled-system or styled-components, but it may be good to mention in the migration guide?

Yes, *all* number values are no longer converted to `px`, the migration guide does not specifically call out `theme.breakpoints`, but it should

> My variants have been css strings, however these no longer work

I think these might have worked before by accident, but it might be possible to support embedded CSS DSLs in the `theme` object (I'd accept a PR with tests if that's straightforward). Since the `theme` is an object, I'd highly recommend using object notation here though.

> defaultProps get rendered after props passed to a component.

Yes, there does appear to be some sort of issue with this. I've asked for help with a PR with failing tests, but haven't had time to dig into it myself – this would require adding React to the test suite

**Comment by ndrsllwngr** [comment] 2019-06-20 19:45
I can confirm 3 (defaultProps).

#### Demo
https://codesandbox.io/s/styled-systembasic-demo-5pku3?fontsize=14

```js
 <Content width={200} pl={1} pr="0px" py="0px">
```
`pl` and `pr` are working fine. But somehow `py` is rendered as `40px` (`defaultProp`) instead of `0px`.
```js
const Content = styled.div`
  ${space};
`;

Content.defaultProps = {
  pt: '40px',
  pr: '15px',
  pb: '40px',
  pl: '15px',
};
```

**Comment by andyford** [comment] 2019-06-25 14:32
oh man... we had a named breakpoints object with values as numbers. We were doing some other calculations based on these numbers, so the upgrade to v5 has really wreaked havoc!

**Comment by jxnblk** [comment] 2019-07-30 18:44
1. Addressing the breakpoints in the migration guide in #642 
2. Using strings for values in a variant in the theme object wasn't intentionally part of the API before, but if there's a simple way to make it work in v5, I'd accept a PR
3. `m` and `mx` are different props, and Styled System can't do much with how React works in that regard. I'd recommend not mixing conflicting CSS properties between the default props and element props

Closing this issue for now, but feel free to open any new issues if needed

**Closed by jxnblk** 2019-07-30 18:44 UTC
