### ISSUE TITLE
Breaking change from 5.0.16 to 5.0.18

### ISSUE THREAD

**Issue by 454de6e** [styled-system/styled-system#644] opened 2019-08-01 04:31 UTC
When upgrading from 5.0.16 to 5.0.18 there seems to be a breaking change. I have not had time to dig deeper, that's why I need to explain with screenshots.

This is a heading rendered with 5.0.16:

<img width="432" alt="5 0 16" src="https://user-images.githubusercontent.com/1482402/62265579-98e34700-b3f2-11e9-9267-b4e4b3684e3a.png">

The corresponding component has these props (note the `mb={3}` which is rendered correctly):

<img width="528" alt="Screen Shot 2019-08-01 at 00 24 45" src="https://user-images.githubusercontent.com/1482402/62265626-d0ea8a00-b3f2-11e9-8e2a-1015be817369.png">

Now I upgrade to 5.0.18 and I see this:

<img width="414" alt="5 0 18" src="https://user-images.githubusercontent.com/1482402/62265679-0ee7ae00-b3f3-11e9-8fcc-8e7a75d4914b.png">

The bottom margin is not rendered correctly. The corresponding component in the DOM tree looks like this (note the `mb={3}` is still there but not honored):

<img width="571" alt="Screen Shot 2019-08-01 at 00 28 28" src="https://user-images.githubusercontent.com/1482402/62265755-5706d080-b3f3-11e9-851c-3cf269c07620.png">

There are less props in 5.0.18 vs 5.0.16.

No idea what is going on, but it does seem to break margins.

**Comment by 454de6e** [comment] 2019-08-01 14:43
Here is some more context of what is happening. The component for which the problem occurs is `Heading` from `rebass`. `Heading` sets as default `m={0}`. Then I set on `Heading` `mt={0}` and `mb={3}`.

With `styled-system` `5.0.16` the margins in the generated CSS show up in this order:

```
margin: 0;
margin-top: 0;
margin-bottom: 1rem;
```
and the component renders with a `1rem` bottom margin.

After upgrading to `styled-system` `5.0.18`, the sequence in the generated CSS rules is different:

```
margin-top: 0;
margin-bottom: 1rem;
margin: 0:
```
and therefore no bottom margin.

**Comment by jxnblk** [comment] 2019-08-01 14:56
Thanks! `5.0.18` was an attempt to fix another ordering bug, and I'm wondering if you're code was taking advantage of that bug. Based on the screenshot, it looks like you have `mt={0} mb={3} m={0}` in JSX, but the panel on the right (React devtools??) is showing a different order.
The last prop defined in order will take precedence over props defined earlier, so if the JSX is correct, the shorthand `margin: 0` will negate the normal margin properties.

Generally, I'd recommend not mixing shorthand CSS with regular properties, but does placing the `m={0}` first correct the issue?

**Comment by jxnblk** [comment] 2019-08-01 14:58
Here are related unit tests to demonstrate the intended behavior https://github.com/styled-system/styled-system/blob/master/packages/space/test/index.js#L152-L186

**Comment by 454de6e** [comment] 2019-08-01 15:06
This is the code: https://github.com/UNDataForum/components/blob/11f40ab7a71ce2e6464122cf756fe11be95f547e/packages/components/src/components/PostPreview/PostPreview.js#L10-L18

`Heading` sets `m={0}` as default, but it is not an explicit prop of `Heading`. I would expect any margins I set explicitly win over defaults.

**Comment by 454de6e** [comment] 2019-08-01 15:15
The obvious workaround based on your unit tests is explicitly set `m={0}` as first prop, i.e.

```
<Heading as="h1" color="text" fontFamily="body" fontSize={fontSize} lineHeight="title" m={0} mt={0} mb={3}>
```
I realize that `styled-system` is much harder than I thought because the cascading nature of CSS in one way or another creeps into the props.

**Comment by jxnblk** [comment] 2019-08-01 15:26
Yeah, default props can be tricky as well, because if you set `m` as a default prop, the `mt` prop is different and won't necessarily override it

**Comment by jxnblk** [comment] 2020-01-02 19:53
Thanks for bringing this to our attention. Closing this because I'm not sure there's anything specific to do here without a bigger change the the internal implementation

**Closed by jxnblk** 2020-01-02 19:53 UTC
