### ISSUE TITLE
Overriding Default Values in Styled-System Variants 

### ISSUE THREAD

**Issue by moshemo** [styled-system/styled-system#499] opened 2019-05-23 12:59 UTC
NOTE:  I am referencing the following functionality in styled-system:  [https://styled-system.com/api#variants](https://styled-system.com/api#variants)

I have the following buttons variant in my `theme.js` file:

```
...
  buttons: {
    flat: {
      color: '#343434',
      boxShadow: 'none',
      backgroundColor: 'transparent',
      transition: 'background-color .2s',
     },
  }
```

This gives a nice, default styling for a flat button.  However, there will be times that I want to override the default color.  Say, something like this:

`<Button variant="flat" color="primary">Flat Button</Button>`

However, this does not work -- because (if I understand correctly), one cannot use props with variants (is that correct?).  If so, I am wondering if there is a way override the styling for `variant="flat"` on a case-by-case basis?

**Comment by jxnblk** [comment] 2019-05-23 16:09
You can add an additional style function to support style props with a variant prop. e.g. `styled('div')(buttonStyle, color)` – that way the end component supports both the `variant` and `color` props

**Comment by moshemo** [comment] 2019-05-23 16:25
I think I'm doing that -- but it still doesn't work.  

Here is the relevant sections of my `Button.js` file:

```
import styled from 'styled-components'
import {
  ...  
  buttonStyle,
  color,
  ...
} from 'styled-system'

import { buttonDefaults, buttonSize } from '../styles/themes/buttons'

const Button = styled('button')`
   ...
  ${buttonSize}
  ${color}
   ...
`

Button.propTypes = {
   ...
   ...color,
  ...buttonStyle,
}

Button.defaultProps = {
  ...buttonDefaults,
  size: `medium`,
}

export default Button

```

And here is the relevant sections of my `buttons.js` file:

```
import { variant } from 'styled-system'

import colors from './colors'

export const buttonDefaults = {
  bg: colors.dark,
  ...
  color: colors.light,
  ...
}

export const buttonStyles = {
  flat: {
    color: colors.dark,
    boxShadow: 'none',
    backgroundColor: 'transparent',
    transition: 'background-color .2s',
  },
  ...  
}
...
```
Or, if you want, you can see the actual code here:
[https://codesandbox.io/s/learningstyledsystemandrebass-8j6im?fontsize=14](https://codesandbox.io/s/learningstyledsystemandrebass-8j6im?fontsize=14)

Either way, I can't figure out why it doesn't work.

**Comment by jxnblk** [comment] 2019-05-23 17:10
Source order matters in CSS, so you'll also need to make sure that the `color` function is passed *after* the `buttonStyle` function, if that might be the issue

**Comment by moshemo** [comment] 2019-05-23 18:57
If I pass the `color` function after the `buttonStyle` function, then `<Button variant='flat' color="primary'>Flat</Button>` then the `color` prop works, but the `variant` prop does not work.  I.e., I get the color I want for the text, but the rest of the button reverts to the default button.

**Comment by jxnblk** [comment] 2019-06-02 16:24
Not sure how to proceed here. It might make sense to open a PR with a failing test to demonstrate? With that maybe someone can look into a solution

**Comment by pzhine** [comment] 2019-06-10 14:38
I ran into the same issue, and figured out what was going on. I was thinking (like @moshemo, I bet) that the order mattered when `compose`ing your system objects. But what actually matters is the order in which the style props are applied to the component.

I have a variant called `textSize` that controls both `fontSize` and `lineHeight`. Sometimes, though, I want to override the lineHeight.

This works as expected
```js
<Text textSize="normal" lineHeight="large">Plenty of space</Text>
```

But this does not (it should do the same as above, because "normal" is the default value of `textSize`)
```js
<Text lineHeight="large">Plenty of space</Text>
```

This may not be a problem `styled-system` but with the order in which defaultProps are applied in React. To force a more explicit order, I changed the following
```js
import React from 'react'
import styled from '@emotion/styled'

import styles, { defaultProps } from './styles'

const Text = styled.div(styles)

Text.defaultProps = defaultProps

export default ({ children, ...others }) => <Text {...others}>{children}</Text>
```

To

```js
import React from 'react'
import styled from '@emotion/styled'

import styles, { defaultProps } from './styles'

const Text = styled.div(styles)

export default ({ children, ...others }) => (
  <Text {...defaultProps} {...others}>
    {children}
  </Text>
)
```

And now all works as expected.

**Comment by nikparo** [comment] 2019-06-15 10:59
I've had a look at the react and styled-system code. It seems to me that the issue is the wrong assumption that `defaultProps` are added to the start of the `props` using something like `props = Object.assign({}, defaultProps, props)`. However, the actual `defaultProps` insertion code adds them to the end of the existing object:

``` js
// Resolve default props
if (type && type.defaultProps) {
  var defaultProps = type.defaultProps;
  for (propName in defaultProps) {
    if (props[propName] === undefined) {
      props[propName] = defaultProps[propName];
    }
  }
}
```

As such the resulting props object in @pzhine's first examples directly above would be:
``` jsx
<Text textSize="normal" lineHeight="large">Plenty of space</Text>
```
``` js
props = {
  // Passed props
  textSize: 'normal',
  lineHeight: 'large',
};
```

Relying on defaultProps the order is switched:
``` jsx
<Text lineHeight="large">Plenty of space</Text>
```
``` js
props = {
  // Passed props
  lineHeight: 'large',

  // Default props
  textSize: 'normal',
};
```

---

The reason this is a problem with styled-system seems to be that the parser loops through the props as such: `for (const key in props) { ... }`, relying on the key order.

**Comment by ransjo** [comment] 2019-06-20 09:48
What if createParser were to iterate over config instead of props, e.g. change
```
for (const key in props) {
  if (!config[key]) continue
  ...
}
```
to
```
for (const key in config) {
  if (props[key] === undefined) continue
  ...
}
```
Then style order would respect config order, e.g.
```
const config = {
  border: {
    property: 'border',
    scale: 'borders',
  },
  borderColor: {
    property: 'borderColor',
    scale: 'colors',
  }
}
```
would have borderColor overriding the border shorthand.

If I am not mistaken, this would generate the same style order as v4 `styled("div")(border, borderColor)`.

**Comment by jxnblk** [comment] 2019-06-20 15:38
@ransjo I’m fairly certain that would negate some of the perf benefits of looping over props

**Comment by nikparo** [comment] 2019-06-21 10:16
@jxnblk I can see that looping over potentially 100+ keys in the config would be a bit slower than looping over a few props, but that could be pretty much negated with something like:
``` js
const propNames = Object.keys(config);
...
const propArray = []

for (const key in props) {
  if (!config[key]) continue
  const idx = propNames.indexOf(key)
  // Create a sparse array of props in the order of config
  propArray[idx] = key
}

// forEach skips holes in sparse arrays.
propArray.forEach(key => {
  ...
});
```

**Comment by angeloashmore** [comment] 2019-06-30 04:06
Just to reiterate what's happening here:

```jsx
import styled from 'styled-components'
import { space } from 'styled-system'

const Button = styled.button(space)

Button.defaultProps = {
  p: 0
}

<Button px={2} py={1}>Hello!</Button>
```

`<Button>` will resolve to a button with no padding despite the `px` and `py` props since `p={0}` is the last prop it receives. `p={0}` is the last prop since `defaultProps` is appended to the `prop` object, not prepended.

```jsx
<Button p={0} px={2} py={1}>Hello!</Button>
```

That example will render the button with the expected `px` and `py` values since `p` is no longer appended to the `prop` object.

@jxnblk Was this not an issue before since `v4` iterated over config keys rather than prop keys? I'm curious how something like `rebass` could be implemented using `v5` since it relies on a very similar setup IIRC.

**Comment by jxnblk** [comment] 2019-06-30 16:01
@angeloashmore Sorry that I haven't had time to dig into this yet, but it would still be helpful to have some failing tests added to work with

> It might make sense to open a PR with a failing test to demonstrate? With that maybe someone can look into a solution

**Comment by angeloashmore** [comment] 2019-06-30 23:49
Sure thing, I’ll try to write up a PR. 👍

**Comment by angeloashmore** [comment] 2019-07-01 05:55
@jxnblk Added a simple test case in PR #590. Let me know if you think there is a better way to test this. I imagine this needs discussion before changing the codebase.

**Comment by jxnblk** [comment] 2019-07-30 16:29
Closing this out for now. I'm in the process of adding tests related to using React `defaultProps`, but there are a few different things being discussed in this issue. Feel free to open a new issue if there are more specific edge cases that should also include tests

**Closed by jxnblk** 2019-07-30 16:29 UTC
