### ISSUE TITLE
Using aliased names within styled-components themeselves

### ISSUE THREAD

**Issue by felipesere** [styled-system/styled-system#425] opened 2019-03-14 21:21 UTC
👋 
This might not be the right place (or inadequate use of styled-system) but I'd love
to be able to write something like

```js
const Unit = styled.div`
  ${fontSize(2)};
  ${pb(1)};
  ${pl(1)};
  align-self: flex-end;
`
```

I was not able grok how I'd import/use the `space` function to make this possible.
Not all my components are reusable as such, but I do like the constraints imposed by using a theme object and styled-system.

**Comment by jxnblk** [comment] 2019-03-14 23:17
Maybe duplicate of #424

**Comment by felipesere** [comment] 2019-03-17 18:14
So this is what I have now added to my project as an experiment what it would look like:
```typescript
import {StandardPropertiesHyphen as CSS} from 'csstype';

export type Source = {[n:number]:number};

export type StyleSources = {
  space: Source,
  fontSizes: Source,
}

type ThemeArg = Readonly<{
  theme: StyleSources
}>

type Value = number | string

type Styling = (n: Value) => (t: ThemeArg) => string

type Alias = {
  property: keyof CSS,
  source: keyof ThemeArg['theme'],
}

const defineAlias = ({source, property}: Alias): Styling => {
  return (n: Value) => {
    if (isNumber(n)) {
      return ({theme}) => {
        const values = get(theme, source);
        return `${property}: ${values[n]}px;`
      }
    } else {
      return (_) => {
        return `${property}: ${n};`
      }
    }
  }
}

function isNumber(x: any): x is number {
    return typeof x === "number";
}

const get = <T, K extends keyof T>(o: T, name: K): T[K]  => o[name];

export const m = defineAlias({property: 'margin', source: 'space'})

export const mt = defineAlias({property: 'margin-top', source: 'space'})
export const mb = defineAlias({property: 'margin-bottom', source: 'space'})
export const ml = defineAlias({property: 'margin-left', source: 'space'})
export const mr = defineAlias({property: 'margin-right', source: 'space'})
```

And I can then use it like so:
```typescript
const Unit = styled.div`
  font-size: 14px;
  align-self: flex-end;
  ${pb(3)}
  ${pl(3)}
  ${m(0)}
`
```

The only reason I prefer this over props + defaults is that I don't really want to expose the props.
Its an outstanding experiment to see if it leads to a valuable separation.

**Comment by jxnblk** [comment] 2019-06-02 14:48
The `@styled-system/css` package sort of handles this use case now so closing this out - see https://styled-system.com/css

**Closed by jxnblk** 2019-06-02 14:48 UTC
