### ISSUE TITLE
Order of space props influences applied spacing

### ISSUE THREAD

**Issue by asterikx** [styled-system/styled-system#1281] opened 2020-04-21 13:11 UTC
**Describe the bug**
Order of styled-system space props influences final spacing.

**To Reproduce**
```jsx
const Box = styled.div`
 ${space}
`

<Box py={2} pt={5} /> // has padding-top 5 (scaled)
<Box pt={5} py={2} /> // has padding-top 2 (scaled)
```

https://codesandbox.io/s/quirky-northcutt-0bgeq

styled-system: 5.1.5

**Expected behavior**
The order of the space props should not change the final spacing. E.g. `padding-top` should take precedence since it is more specific than `padding-y`. 

**Additional context**
This is all the more problematic when using React's `defaultProps`, as these are applied _after_ the props that are passed to the component:

```jsx
const Box = styled.div`
  ${space}
`;

Box.defaultProps = {
  py: 2
};

<Box pt={5} /> // has padding-top 2 (scaled) since default prop px is applied after pt
```

**Comment by jxnblk** [comment] 2020-05-12 15:56
Thanks, this is a duplicate of #1058

**Closed by jxnblk** 2020-05-12 15:56 UTC
