### ISSUE TITLE
Removing props from styled-components

### ISSUE THREAD

**Issue by benjamingeorge** [styled-system/styled-system#387] opened 2019-02-14 18:00 UTC
is there a best practice way to get styled-components to not add all these style specific attributes to the resulting DOM element?   
```html
<a href="/" color="black.0" fill="text" width="100%,initial" display="inline-block" class="sc-gzVnrw eeYwIX">Continue Shopping</a>
```

**Comment by ckeeney** [comment] 2019-02-15 01:41
likely related or a duplicate of https://github.com/rebassjs/rebass/issues/570

**Comment by jxnblk** [comment] 2019-02-17 23:13
See https://github.com/styled-components/styled-components/issues/439

**Comment by ckeeney** [comment] 2019-02-18 21:11
For those that stumble across this issue looking for a workaround, https://github.com/styled-components/styled-components/pull/2093#issuecomment-461510706 is working well for me.

**Comment by jxnblk** [comment] 2019-06-02 14:43
There’s a guide for this now. Feel free to PR any improvements to this doc that you might have https://styled-system.com/guides/removing-props-from-html

**Closed by jxnblk** 2019-06-02 14:43 UTC

**Comment by netojose** [comment] 2019-07-26 14:23
Just rename your props. Use prop names different of valid HTML attributes. Styled components will filter and don't will show them on HTML
